name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - uses: actions/checkout@v4

    # 2. Configura JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 3. Ejecuta Maven para compilar y ejecutar las pruebas
    - name: Build with Maven
      run: mvn clean test

    # 4. Publicar el reporte de Cucumber como artefacto
    - name: Upload Cucumber Reports
      if: always()  # Asegura que este paso se ejecute incluso si las pruebas fallan
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-reports
        path: target/cucumber-reports/cucumber-reports.html

