name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona el repositorio
    - uses: actions/checkout@v4

    # 2. Configura JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 3. Ejecuta Maven para compilar y ejecutar las pruebas
    - name: Build with Maven
      run: mvn clean test

    # 4. Crear carpeta para guardar reportes
    - name: Create reports directory
      run: mkdir -p reports

    # 5. Mover el informe de Cucumber a la carpeta 'reports'
    - name: Move Cucumber Reports
      run: |
        if [ -f target/cucumber-reports.html ]; then
          mv target/cucumber-reports.html reports/
        fi

